config/routes.rb
Rails.application.routes.draw do

  resources :people, only: [:index, :new, :create]
  resources :companies
  root to: 'people#index'

  namespace :api do
    resources :people, only: :index
    resources :companies, only: :index
  end
end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Company < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: { maximum: 50 }

  has_many :people
end

app/controllers/api/companies_controller.rb
class Api::CompaniesController < ActionController::API
  def index
    if params[:name].present?
      companies = Company.where('LOWER(name) LIKE ?', "%#{params[:name]&.downcase}%").page(params[:page] || 1).per(params[:per_page] || 10)
    else
      companies = Company.all.page(params[:page] || 1).per(10)
    end

    render json: { meta: pagination_meta(companies), data: companies }, status: 200
  end

  private

  def pagination_meta(scope)
    {
      current_page: scope.current_page,
      next_page: scope.next_page,
      prev_page: scope.prev_page,
      total_pages: scope.total_pages,
      total_count: scope.total_count
    }
  end
end

app/controllers/api/v1/companies_controller.rb
class Api::V1::CompaniesController < Api::V1::BaseController
  include ApiAuthenticable

  skip_before_action :verify_authenticity_token

  def create
    companies = Company.create(companies_attributes)
    if authenticate_user && companies
      render json: companies, each_serializer: CompanySerializer
    else
      render json: { message: 'Invalid email or password' }
    end
  end

  private
    def companies_attributes
      params.permit(companies: [:name]).require(:companies)
    end
end

app/controllers/api/v1/company_controller.rb
class Api::V1::CompanyController < ApplicationController
  def show
    company = company.find_by(name: params[:name]).page params[:page]

    if company
      render json: company, status: 200
    else
      render json: {error: "Company Not Found."}
    end
  end

  private

  def company_attributes
    params.require(:company).permit(:name)
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :load_company, only: [:edit, :update]

  def index
    @companies = Company.all.page(params[:page] || 1).per(10)
  end

  def new
    @company = Company.new
  end

  def edit; end

  def create
    if Company.create(company_attributes)
      redirect_to companies_path, notice: 'Successfully created entry'
    else
      render :create, alert: 'Unsuccessfully created entry'
    end
  end

  def update
    if @company.update(company_attributes)
      redirect_to companies_path, notice: 'Successfully updated entry'
    else
      render :edit, alert: 'Unsuccessfully created entry'
    end
  end

  private

  def company_attributes
    params.require(:company).permit(:name)
  end

  def load_company
    @company = Company.find(params[:id])
  end
end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
    def index
        @companies = Company.all
    end
    
    def new
        @company = Company.new
    end
    
    def create
        if Company.create(company_attributes).valid?
          redirect_to company_index_path, notice: 'Successfully created entry'
        else
          redirect_to company_index_path, alert: 'Unsuccessfully created entry'
        end
    end  
      

    ### COMPANY API SECTION ###

    #Get a list of companies based off of filter. :name :page :per_page
    #Results must be case insensitve and partial match
    def company_list
        #Get a list of all companies who have a partial name match, case insensitive and return the results
        @companies = Company.where("lower(name) LIKE ?", "%" + params[:name].downcase + "%").page(params[:page]).per(params[:per_page])

        render json: @companies
    end

    #Add companies to the database
    def company_add
        #Basic Authentication -> Will need upgraded to something like Devise

        if params[:username] == "AcceptedUser" and params[:password] == "AcceptedPassword"
            #User authenticated. Add new companies and return the results
            companies = Company.create(companies_attributes)

            render json: @companies
        else
            #User authntication failed. Return an error message
            render json: {msg: "Invalid username or password"}
        end
    end
    ### END PEOPLE API SECTION ###

    private

    def company_attributes
        params.require(:company).permit(:name)
    end

    def companies_attributes
        params.permit(companies: [:name]).require(:companies)
    end
end

app/helpers/api/v1/company_helper.rb
module Api::V1::CompanyHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.each do |error| %>
          <li><%= error.full_company %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, required: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/edit.html.slim
h2 Creating an entry

= form_for @company, class: 'row' do |f|
  .col-auto
    = f.label :name, class: 'form-label'
    = f.text_field :name, class: 'form-control'
  .col-auto.mt-4
    = f.submit class: 'btn btn-primary'

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company)  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/index.html.slim
h2 Viewing companies

table.table
  thead
    tr
      th[scope="col"] ID
      th[scope="col"] Name
      th[scope="col"] Created At
      th[scope="col"] Actions
  tbody
    - @companies.each do |company|
      tr
        th[scope="row"]= company&.id
        td= company.try(:name)
        td= company.try(:created_at).strftime("%m/%d/%Y")
        td= link_to "Edit", edit_company_path(company), class: 'btn btn-primary'

.row.justify-content-between
  .col-4
    = paginate @companies, theme: 'bootstrap3'
    = page_entries_info @companies
  .col-4
    = link_to "New Company", new_company_path, class: 'btn btn-success'

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/new.html.slim
h2 Creating an entry

= form_for @company, class: 'row' do |f|
  .col-auto
    = f.label :name, class: 'form-label'
    = f.text_field :name, class: 'form-control'
  .col-auto.mt-4
    = f.submit class: 'btn btn-primary'

app/views/companies/search.html.slim
h1 Companies#search
p Find me in app/views/companies/search.html.slim

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>